### ISSUE TITLE
Unix socket not accessible when using --detached mode

### ISSUE THREAD

**Issue by schickling** [F1bonacc1/process-compose#364]
# Unix socket not accessible when using --detached mode

## Description
When starting process-compose with Unix socket mode (`-U`) and detached mode (`--detached`), the socket file appears to be created but is not accessible for client commands like `process list`.

## Environment
- Process Compose Version: v1.64.1
- OS: Linux 6.1.35
- Platform: linux

## Steps to Reproduce

1. Start process-compose with Unix socket and detached mode:
```bash
process-compose -U -u .process-compose.sock up -t=false --detached
```

2. Verify the socket file exists:
```bash
ls -la .process-compose.sock
# Output: srwxr-xr-x 1 user users 0 Jul  5 15:22 .process-compose.sock
```

3. Try to list processes:
```bash
process-compose -u .process-compose.sock process list
```

## Expected Behavior
The `process list` command should connect to the Unix socket and return the list of running processes.

## Actual Behavior
The command fails with:
```
FTL failed to list processes error="Get \"http://unix/processes\": dial unix .process-compose.sock: connect: no such file or directory"
```

Even though:
- The socket file exists on the filesystem
- The process-compose process is running
- `lsof` shows the process has the socket open

## Additional Information

- The same issue occurs whether using `-U` alone or `-U -u <path>`
- When running without `--detached` (just backgrounded with `&`), the socket still has the same issue
- All managed processes (defined in process-compose.yaml) are running correctly
- This happens consistently across multiple attempts

## Workarounds Attempted
1. Using explicit socket path with `-u`
2. Running without `--detached` flag
3. Setting `PC_SOCKET_PATH` environment variable

None of these resolved the socket communication issue.

## Question
Is this a known limitation, a bug, or are we using the Unix socket feature incorrectly? The documentation suggests Unix sockets should work as a drop-in replacement for TCP mode, but we're unable to get client commands working with it.

Any guidance would be appreciated!

**Comment by schickling** [comment]
## Update: Attach command causes panic

When trying to use `process-compose attach`, the program crashes with a nil pointer dereference:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb88f4a]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/application.go:297 +0x45
panic({0xd431a0?, 0x1e2b6a0?})
        runtime/panic.go:792 +0x132
github.com/gorilla/websocket.(*Conn).WriteMessage(0xc0011f8b36?, 0x0?, {0xc00114705a, 0x2, 0x2})
        github.com/gorilla/websocket@v1.5.3/conn.go:760 +0x2a
github.com/f1bonacc1/process-compose/src/client.(*LogClient).CloseChannel(0xc000800460)
        github.com/f1bonacc1/process-compose/src/client/logs.go:64 +0x56
```

The crash occurs in the WebSocket connection handling, suggesting the connection pointer is nil when trying to write a message.

This happens consistently when:
1. Starting process-compose with TCP mode: `process-compose -p 8377 up -t=false`
2. Trying to attach: `process-compose -p 8377 attach`

The processes are running fine, but the attach functionality is broken.

**Comment by schickling** [comment]
## Resolution: Using --no-server flag

After further investigation, we found that the root cause of our issues was port conflicts between process-compose's HTTP server (default port 8080) and our application.

The simplest solution is to use the `--no-server` flag:
```bash
process-compose --no-server up -t=false
```

This eliminates:
- Port conflict issues
- The WebSocket crash when using attach
- Complex port allocation logic
- Unix socket issues

While it would still be nice to have working Unix sockets for management, the `--no-server` approach is much simpler and works reliably. The processes run fine and can be monitored through log files.

Perhaps the documentation could highlight this option for users who don't need the HTTP/WebSocket management interface.

**Comment by schickling** [comment]
## Update: Closing issue

After further investigation, we've decided to work with the current limitations rather than trying to fix them. Our approach:

1. **Simple pc-socket wrapper** that starts process-compose with `-U` flag
2. **Documented known issues** in our README and internal docs
3. **Workarounds** for common problems (checking processes directly, using log files instead of attach)

While it would be nice to have reliable Unix socket communication and a working attach command, we can work around these issues for now. The processes run fine, which is what matters most.

Feel free to close this issue or keep it open for tracking. We'll revisit if these become blocking issues in the future.

**Comment by liaowang11** [comment]
I'm getting the same SIGSEGV error when trying to attach to process compose, and i don't think it's a port conflicts as 8080 is not used by any other applications on my machine. It would be nice to have a fix for this. 
Version: v1.64.1
```
❯ process-compose attach
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x104aba654]

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1()
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/application.go:297 +0x4c
panic({0x104dbbe80?, 0x105cd38b0?})
        runtime/panic.go:792 +0x124
github.com/gorilla/websocket.(*Conn).WriteMessage(0x140000ef2c0?, 0x140000ef2c0?, {0x1400113992a, 0x2, 0x2})
        github.com/gorilla/websocket@v1.5.3/conn.go:760 +0x24
github.com/f1bonacc1/process-compose/src/client.(*LogClient).CloseChannel(0x14000274500)
        github.com/f1bonacc1/process-compose/src/client/logs.go:64 +0x60
github.com/f1bonacc1/process-compose/src/client.(*PcClient).UnSubscribeLogger(0x7?, {0x140002d07f7?, 0x7?}, {0x140002d0980?, 0x7?})
        github.com/f1bonacc1/process-compose/src/client/client.go:87 +0x20
github.com/f1bonacc1/process-compose/src/tui.(*pcView).unFollowLog(0x140000f7d40)
        github.com/f1bonacc1/process-compose/src/tui/log-operations.go:73 +0x48
github.com/f1bonacc1/process-compose/src/tui.(*pcView).onTableSelectionChange(0x140000f7d40, 0x10447f848?, 0x104485330?)
        github.com/f1bonacc1/process-compose/src/tui/proc-table.go:161 +0x94
github.com/rivo/tview.(*Table).InputHandler.func1(0x14001102da0, 0x104af5140?)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/table.go:1684 +0x890
github.com/rivo/tview.(*Table).InputHandler.(*Box).WrapInputHandler.func2(0x14000666000?, 0x1400111d880?)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/box.go:167 +0x54
github.com/rivo/tview.(*Grid).InputHandler.func1(0x14001102da0, 0x1400111d880)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/grid.go:664 +0x21c
github.com/rivo/tview.(*Grid).InputHandler.(*Box).WrapInputHandler.func2(0x14000190f30?, 0x1400111d880?)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/box.go:167 +0x54
github.com/rivo/tview.(*Pages).InputHandler.func1(0x14001102da0, 0x1400111d880)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/pages.go:323 +0xa8
github.com/rivo/tview.(*Pages).InputHandler.(*Box).WrapInputHandler.func2(0x140006164e0?, 0x14000077938?)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/box.go:167 +0x54
github.com/rivo/tview.(*Application).Run(0x1400018e2a0)
        github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/application.go:416 +0x83c
github.com/f1bonacc1/process-compose/src/tui.RunTUI({0x104ec5858?, 0x140002744b0?}, {0x140002caaf0?, 0x0?, 0x104dab420?})
        github.com/f1bonacc1/process-compose/src/tui/view.go:598 +0x38
github.com/f1bonacc1/process-compose/src/cmd.startTui({0x104ec5858, 0x140002744b0}, 0x0)
        github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:140 +0x55c
github.com/f1bonacc1/process-compose/src/cmd.init.func1(0x105ce8f40?, {0x104b8a395?, 0x4?, 0x104b8a3dd?})
        github.com/f1bonacc1/process-compose/src/cmd/attach.go:12 +0x30
github.com/spf13/cobra.(*Command).execute(0x105ce8f40, {0x105d2f460, 0x0, 0x0})
        github.com/spf13/cobra@v1.9.1/command.go:1019 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x105ceb040)
        github.com/spf13/cobra@v1.9.1/command.go:1148 +0x384
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/f1bonacc1/process-compose/src/cmd.Execute()
        github.com/f1bonacc1/process-compose/src/cmd/root.go:71 +0x24
main.main()
        github.com/f1bonacc1/process-compose/src/main.go:8 +0x1c
```

**Comment by F1bonacc1** [comment]
Hey @schickling, @liaowang11,

Thanks for filing thin issue.
I tried to reproduce it following the steps you provided, but after many tried it works as expected for me:

<img width="1209" height="868" alt="Image" src="https://github.com/user-attachments/assets/636185f0-cdd8-445e-a1f8-c895aad30495" />

Does it happen all the time?
Is there anything else you recommend trying to reproduce it?

**Comment by liaowang11** [comment]
Yes, it happens all the time.  Here this way to reproduce under version 1.64.1:
```shell
❯ /nix/store/1f768ii5k8l0w31g4xijjpiwn86jxymf-process-compose-1.64.1/bin/process-compose version
Process Compose
Version:        v1.64.1
Commit:         d1fd7c3
Date (UTC):     2025-05-10T16:18:23Z
License:        Apache-2.0
Discord:        https://discord.gg/S4xgmRSHdC

Written by Eugene Berger
```

The process compose file used:
```shell
❯ cat process-compose.yaml
is_strict: true
processes:
  sleep1:
    availability:
      restart: on_failure
    command: exec sleep 100
  sleep2:
    availability:
      restart: on_failure
    command: exec sleep 100
version: '0.5'
```

```shell
❯ /nix/store/1f768ii5k8l0w31g4xijjpiwn86jxymf-process-compose-1.64.1/bin/process-compose --config process-compose.yaml --unix-socket pc.sock up -D
Starting Process Compose in detached mode. Use 'process-compose attach' to connect to it or 'process-compose down' to stop it
❯ /nix/store/1f768ii5k8l0w31g4xijjpiwn86jxymf-process-compose-1.64.1/bin/process-compose --unix-socket pc.sock attach
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x102b36804]
```

I have noticed that if I don't press any key the crash will not be triggered. Happy to supply any more information if needed. 
Thanks for your work.

**Comment by F1bonacc1** [comment]
Hi @liaowang11,

Thank you for your quick response and the detailed repro steps.
I tried them, but the result is the same for me:

<img width="1162" height="374" alt="Image" src="https://github.com/user-attachments/assets/3ac77ca3-c6ee-4d6c-9ed7-9a13f7f67251" />

Please try with v1.73.0 and let me know if it fixes the issue for you.

**Comment by liaowang11** [comment]
I think I find the culprit. If I configure http proxy in my shell, there will be the crash, while turning off fix the issue.
But I don't understand why it's related.

**Comment by F1bonacc1** [comment]
Thank you for this lead @liaowang11 
I managed to reproduce it with a dummy proxy in my shell:
```shell
export HTTP_PROXY=http://localhost:3128
```
I fixed the crash, but of course there are no logs in this case.
Can you please define:
```shell
export NO_PROXY="$NO_PROXY,unix"
```
And let me know if it works?

**Comment by liaowang11** [comment]
> Thank you for this lead [@liaowang11](https://github.com/liaowang11) I managed to reproduce it with a dummy proxy in my shell:
> 
> export HTTP_PROXY=http://localhost:3128
> I fixed the crash, but of course there are no logs in this case. Can you please define:
> 
> export NO_PROXY="$NO_PROXY,unix"
> And let me know if it works?

Am I supposed to build the latest version and try this?

**Comment by F1bonacc1** [comment]
> Am I supposed to build the latest version and try this?

No, no. Just define this variable, and it should work:
```shell
export NO_PROXY="$NO_PROXY,unix"
```
The crash fix will be part of the next release. But with the above env the PC shouldn't crash for you anymore.

**Comment by liaowang11** [comment]
> > Am I supposed to build the latest version and try this?
> 
> No, no. Just define this variable, and it should work:
> 
> export NO_PROXY="$NO_PROXY,unix"
> The crash fix will be part of the next release. But with the above env the PC shouldn't crash for you anymore.

Oh sure. I tested and it works. Thanks for your help.

**Comment by schickling** [comment]
I can confirm this issue is still reproducible in v1.64.1. Here are detailed reproduction steps:

## Environment
- **OS**: Linux 6.1.35 #1-NixOS SMP PREEMPT_DYNAMIC (x86_64)
- **Terminal**: xterm-256color
- **Go version**: go1.24.5 linux/amd64
- **Process Compose version**: v1.64.1 (commit: d1fd7c3, built: 2025-05-10T16:18:23Z)

## Minimal Reproduction

### 1. Configuration file (`process-compose.yaml`)
```yaml
version: "0.5"
http_server:
  port: 8081
processes:
  test-process:
    command: "sleep 30"
    restart: always
    
  another-process:
    command: "echo 'Hello from process 2' && sleep 60"
    restart: always
```

### 2. Start process-compose
```bash
process-compose up --tui=false -p 8082
```
(Note: Using `--tui=false` to avoid TUI startup issues, and custom port to avoid conflicts)

### 3. Attempt to attach (in another terminal)
```bash
process-compose attach test-process -p 8082
```

### 4. Result - Consistent Panic
```
panic: close of nil channel

goroutine 1 [running]:
github.com/gdamore/tcell/v2.(*tScreen).finish(...)
	github.com/gdamore/tcell/v2@v2.8.1/tscreen.go:683
sync.(*Once).doSlow(0xc0002232e8?, 0xc000013680?)
	sync/once.go:78 +0xab
sync.(*Once).Do(...)
	sync/once.go:69
github.com/gdamore/tcell/v2.(*tScreen).Fini(0x5?)
	github.com/gdamore/tcell/v2@v2.8.1/tscreen.go:679 +0x3b
github.com/rivo/tview.(*Application).Stop(0xc0001bc2a0)
	github.com/rivo/tview@v0.0.0-20250330220935-949945f8d922/application.go:607 +0x8a
github.com/f1bonacc1/process-compose/src/tui.(*pcView).handleShutDown(0xc000229a00)
	github.com/f1bonacc1/process-compose/src/tui/view.go:408 +0x9a
github.com/f1bonacc1/process-compose/src/tui.RunTUI({0xfbdf38?, 0xc0000344b0?}, {0xc000222fc0?, 0x1e55d60?, 0xd32680?})
	github.com/f1bonacc1/process-compose/src/tui/view.go:600 +0x91
github.com/f1bonacc1/process-compose/src/cmd.startTui({0xfbdf38, 0xc0000344b0}, 0x0)
	github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:140 +0x63d
github.com/f1bonacc1/process-compose/src/cmd.init.func1(0x1e41040?, {0xe3a4c9?, 0x4?, 0xe3a511?})
	github.com/f1bonacc1/process-compose/src/cmd/attach.go:12 +0x25
github.com/spf13/cobra.(*Command).execute(0x1e41040, {0xc0002b2a80, 0x3, 0x3})
	github.com/spf13/cobra@v1.9.1/command.go:1019 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x1e43140)
	github.com/spf13/cobra@v1.9.1/command.go:1148 +0x46f
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.9.1/command.go:1071
github.com/f1bonacc1/process-compose/src/cmd.Execute()
	github.com/f1bonacc1/process-compose/src/cmd/root.go:71 +0x1a
main.main()
	github.com/f1bonacc1/process-compose/src/main.go:8 +0xf
```

## Key Observations

1. **100% reproducible**: Every attempt to use `attach` command results in this panic
2. **Affects all processes**: Both `test-process` and `another-process` cause the same panic
3. **TUI-related**: The panic occurs in the TUI shutdown code path (`tScreen.finish()`)
4. **Race condition**: Appears to be a nil channel being closed during TUI cleanup

## Analysis

The issue is in the TUI cleanup sequence. Looking at the stack trace:
- `attach.go:12` calls `startTui()`  
- `project_runner.go:140` calls `RunTUI()`
- `view.go:600` calls `handleShutDown()`
- `view.go:408` calls `tview.Application.Stop()`
- `application.go:607` calls `tScreen.Fini()`
- `tscreen.go:679` calls `tScreen.finish()` 
- **PANIC** at `tscreen.go:683` trying to close a nil channel

The root cause seems to be that the TUI is being torn down before it's fully initialized, or there's improper synchronization in the channel lifecycle management.

## Workaround

Currently, there's no workaround for the `attach` command. Users must rely on:
- Log file monitoring (`tail -f process-compose.log`)
- Direct process inspection (`ps aux | grep <process>`)
- HTTP API endpoints (if accessible)

This significantly impacts the debugging experience for process-compose users.

@eugene-berger Would you like me to provide any additional debugging information or test specific scenarios?

**Comment by F1bonacc1** [comment]
Thanks for sharing that @schickling.
I tried your repro steps and I noticed 2 interesting facts:

1. In your `process-compose.yaml` you use an attribute `http_server.port`. I wonder where does this attribute come from, as it is not part of PC code base. Are you using a forked version of PC? Do you experience the crash if both ports are the same?
2. It doesn't crash for me. I tried many times.

<img width="1075" height="287" alt="Image" src="https://github.com/user-attachments/assets/1efca021-b06b-448b-a733-eb0b8bb432b3" />

Will you be willing to try the same with v1.73.0?

**Comment by schickling** [comment]
## Update: Tested v1.73.0 with suggested workarounds ❌

I've tested the latest version v1.73.0 with both suggested workarounds, but unfortunately **the issue still persists**.

### Quick reproduction

I've created a minimal reproduction repository: **https://github.com/schickling-repros/process-compose-attach-panic-repro**

Just run:
```bash
git clone https://github.com/schickling-repros/process-compose-attach-panic-repro.git
cd process-compose-attach-panic-repro
chmod +x test-attach-panic.sh
./test-attach-panic.sh
```

### Test Results (v1.73.0, commit: 81ef36d)

❌ **Standard TCP connection**: `panic: close of nil channel`  
❌ **With NO_PROXY environment variable**: Same panic  
❌ **Unix domain sockets + NO_PROXY**: Same panic  

Tested on Linux 6.1.35 #1-NixOS SMP PREEMPT_DYNAMIC (x86_64) with xterm-256color terminal and Go 1.24.5. The reproduction has been verified on an actual Linux machine and consistently produces the same results.

### Stack trace (consistent across all scenarios)
```
panic: close of nil channel

goroutine 1 [running]:
github.com/gdamore/tcell/v2.(*tScreen).finish(...)
	/home/eugene/go/pkg/mod/github.com/gdamore/tcell/v2@v2.8.1/tscreen.go:683
sync.(*Once).doSlow(0xc0002e30b8?, 0xc0000116e0?)
	/usr/local/go/src/sync/once.go:78 +0xab
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:69
github.com/gdamore/tcell/v2.(*tScreen).Fini(0x5?)
	/home/eugene/go/pkg/mod/github.com/gdamore/tcell/v2@v2.8.1/tscreen.go:679 +0x3b
github.com/rivo/tview.(*Application).Stop(0xc0000141e0)
	/home/eugene/go/pkg/mod/github.com/rivo/tview@v0.0.0-20250625164341-a4a78f1e05cb/application.go:632 +0x8a
github.com/f1bonacc1/process-compose/src/tui.(*pcView).handleShutDown(0xc0001b9d40)
	/home/eugene/projects/go/process-compose/src/tui/view.go:412 +0x9a
github.com/f1bonacc1/process-compose/src/tui.RunTUI({0x13ab678?, 0xc000032550?}, {0xc0002e2e70?, 0x23d8fe0?, 0x104ff80?})
	/home/eugene/projects/go/process-compose/src/tui/view.go:606 +0x91
github.com/f1bonacc1/process-compose/src/cmd.startTui({0x13ab678, 0xc000032550}, 0x0)
	/home/eugene/projects/go/process-compose/src/cmd/project_runner.go:145 +0x63d
github.com/f1bonacc1/process-compose/src/cmd.init.func1(0x23c4080?, {0x1172166?, 0x4?, 0x11721ae?})
	/home/eugene/projects/go/process-compose/src/cmd/attach.go:12 +0x25
```

The crash appears to be a fundamental TUI initialization/cleanup race condition unrelated to proxy configuration. The attach command fails during TUI teardown, possibly because the TUI was never properly initialized.

@eugene-berger The suggested workarounds unfortunately don't resolve this specific panic. Is there a different build or approach I should try?

**Comment by F1bonacc1** [comment]
Hi @schickling,

Thanks for helping me debug the issue.
I tried the repro step:

```shell
./test-attach-panic.sh
Starting process-compose in background...
Waiting for process-compose to start...
[another-process	] Hello from process 2
Attempting to attach to test-process (this should panic)...
If you see this message, the attach command worked (unexpected!)
```

I dove deeper into the `tview` and the `tcell` 3rd party. I think this is related to this error: "character set not supported".
Can you please share the PC client log immediately after the crash? It should have the exact error.
Usually, the client log is saved under `/tmp/process-compose-$USER-client.log`

BTW, it seems that the same issue should also happen in the regular TUI mode, not only in an `attach` scenario.

EDIT:
Please also share those env variables:
1. LC_ALL
2. LC_CTYPE
3. LANG

**Comment by schickling** [comment]
## Evidence for the crash investigation

Thank you @F1bonacc1 for the investigation! Here's the requested evidence:

### 1. Client Log
The PC client log from `/tmp/process-compose-schickling-client.log` shows the exact error you suspected:

```
[90m25-08-15 09:08:00.746[0m [32mINF[0m [1mProcess Compose v1.73.0[0m
[90m25-08-15 09:08:00.761[0m [31mERR[0m [1mTUI stopped[0m [36merror=[0m[31m[1m"open /dev/tty: no such device or address"[0m[0m
```

### 2. Environment Variables
```bash
LC_ALL: (not set)
LC_CTYPE: en_US.UTF-8
LANG: en_US.UTF-8
```

### 3. Regular TUI Mode Also Affected
You were absolutely correct! The issue also occurs in regular TUI mode, not just in attach:

```bash
./process-compose up -p 8086
```

Results in the same panic:
```
panic: close of nil channel

goroutine 52 [running]:
github.com/gdamore/tcell/v2.(*tScreen).finish(...)
	/home/eugene/go/pkg/mod/github.com/gdamore/tcell/v2@v2.8.1/tscreen.go:683
[... same stack trace ...]
github.com/f1bonacc1/process-compose/src/tui.RunTUIAsync.func1()
	/home/eugene/projects/go/process-compose/src/tui/view.go:597 +0x78
```

### 4. Root Cause Analysis
The key issue is **`"open /dev/tty: no such device or address"`**. This explains why:
- Your tests work (you have proper TTY access)
- Our tests fail (running in an environment without `/dev/tty` access)
- The panic always occurs in TUI initialization/cleanup

This is indeed a "character set not supported" / TTY access issue as you suspected. The TUI fails to initialize properly due to lack of TTY device access, which then causes the nil channel panic during cleanup.

### 5. Testing Environment Context
We're running this on a remote server environment where `/dev/tty` access may be restricted or unavailable, which explains the consistent reproduction while your local tests work fine.

Would you like me to test any specific workarounds or provide additional debugging information?

**Comment by schickling** [comment]
## Update: TTY Dependency Identified

Thanks for the investigation @F1bonacc1! You were right about the TTY issue. I've confirmed that:

**Root cause**: The panic only occurs in **non-TTY environments** where `/dev/tty` is unavailable.

**Reproduction confirmed**:
- ❌ Direct execution: `./process-compose up` → `panic: close of nil channel`
- ✅ With pseudo-TTY: `script -qec "./process-compose up" /dev/null` → works perfectly

**Why this matters**: This affects legitimate use cases like:
- CI/CD pipelines
- Docker containers (without TTY allocation)
- SSH automation (`ssh user@host "process-compose up"`)
- Background services

**The issue**: While the behavior is expected (TUI needs TTY), the error handling could be improved. Instead of a cryptic panic, users would benefit from a clear message like "TTY required for TUI mode. Use --tui=false for non-interactive environments."

The reproduction repository remains useful for testing error handling improvements in non-TTY scenarios.

**Comment by F1bonacc1** [comment]
Thank you for confirming that @schickling.

I added better error handling:
```shell
setsid ./bin/process-compose
25-08-16 18:59:51.163 FTL TUI startup error error="open /dev/tty: no such device or address"
```
It will be part of the next release.
